name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Build and test on ${{ matrix.os }} ${{ matrix.compiler }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            cmake_generator: "-G \"Visual Studio 16 2019\" -A x64"
          - os: windows-2019
            cmake_generator: "-G \"Visual Studio 16 2019\" -A Win32"
          - os: macOS-10.15
            privledges: "sudo"
          - os: ubuntu-20.04
            privledges: "sudo"
            build_docs: "-DBUILD_DOCS=ON"
            analyzers: "cppcheck"
            extras: "python3-breathe python3-sphinx doxygen cppcheck"
          - os: ubuntu-20.04
            privledges: "sudo"
            compiler: "clang"
            scan: "scan-build --status-bugs"
            extras: "clang clang-tools"

    steps:
      - uses: actions/checkout@v2

      - name: Install extra dependencies
        if: ${{ matrix.extras != '' }}
        run: |
            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ${{ matrix.extras }}

      - name: Setup clang toolchain
        if: ${{ matrix.compiler == 'clang' }}
        run: |
            echo "CC=/usr/bin/clang"    >> $GITHUB_ENV
            echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

      - name: Configure
        shell: bash
        run: |
          ${{ matrix.scan }} cmake -S . -B build \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON  \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=ON \
            -DBUILD_APPS=ON \
            ${{ matrix.build_docs }} \
            -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib \
            ${{ matrix.cmake_generator }} \

      - name: Run cppcheck
        shell: bash
        if: ${{ matrix.analyzers == 'cppcheck' }}
        run: |
          cppcheck \
            --enable=style,portability,performance,warning \
            --library=posix \
            --inline-suppr \
            --project=build/compile_commands.json \
            --error-exitcode=1 \

      - name: Build and Install
        shell: bash
        run: |
            ${{ matrix.privledges }} cmake \
              --build build \
              --config Release \
              --target install \

      - name: Test
        shell: bash
        run: |
            cd build
            ctest -C Release --output-on-failure
